#You are given two strings s and t.
#String t is generated by random shuffling string s and then add one more letter at a random position.
#Return the letter that was added to t.
#Solution - Use bitwise XOR on each character, using ascii value of eac of them(using ord()). Since XOR of same values result in 0, the result would be ascii value of the
#unique character. Then converst ASCII value to character using chr()

class Differencebtwstrings():
    def findingdifference(self,s,t):
        result = 0
        u = s+t
        for i in range(0,len(u)):
            result = result ^ ord(u[i])

        return(chr(result))

d = Differencebtwstrings()
print(d.findingdifference('abtui','abtyui'))



